- name: Create .kalite directory
  file: path=/mnt/storage/.kalite state=directory

- name: Create symlink for .kalite directory
  file: src=/mnt/storage/.kalite dest=/root/.kalite state=link

- name: Create .usrsharekalite directory
  file: path=/mnt/storage/.usrsharekalite state=directory

- name: Create symlink for .usrsharekalite directory
  file: src=/mnt/storage/.usrsharekalite dest=/usr/share/kalite state=link

- name: Create symlink for .content directory
  file: src=/mnt/storage/materials/content dest=/mnt/storage/.kalite/content state=link

#- name: Copy ka-lite sdist over
#  copy: src=ka-lite-static-0.16.b2.tar.gz dest=/mnt/storage/

- name: Untar ka-lite sdist
  unarchive: src=/mnt/storage/materials/ka-lite-static-0.16.b2.tar.gz dest=/mnt/storage copy=no

- name: Installing ka-lite
  shell: python setup.py install chdir=/mnt/storage/ka-lite-static-0.16.b2

- name: Unpacking assessment items
  shell: PYTHONPATH=/mnt/storage/ka-lite-static-0.16.b2/dist-packages python kalitectl.py manage unpack_assessment_zip /mnt/storage/materials/khan_assessment.zip chdir=/mnt/storage/ka-lite-static-0.16.b2
